### ISSUE TITLE
Versioning ADR

### ISSUE THREAD

**Issue by Sander3003** [openscd/open-scd-core#119]
As a Developer
I would like to know how to handle mwc/Lit versions
So I know when is lead to a plug-in failing

Problem:
When a plug-ins are using different verions for the same dependency (e.g. MWC/LIT) leads to problems/faillures.
Example: OSCD-action icon

Possible solutions (for now):
Scope MWC
Prepare for custom register (polyfill)
Fix MWC version

Long term solution:
Scoped custem registies (expected in the browsers)

**Comment by pascalwilbrink** [comment]
As discussed earlier, we have MWC elements pinned at Version 0.27.0 (Latest).
The list of MWC components can be found here:
https://github.com/material-components/material-web#readme

**Comment by Sander3003** [comment]
@trusz can we close this one?

**Comment by Sander3003** [comment]
Not relevant for now
