### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by ca-d** [openscd/open-scd-core#31]

**Comment by juancho0202** [comment]
- Include a mention regarding why <open-scd> gets its properties from separate mixins. I'm thinking being explicit that it is not for re-usability of these mixins but rather for testing purposes.
- The choice of yarn as a package manager and the including of .yarn/* files should be mentioned as well. Here are some refs regarding that:
  - https://yarnpkg.com/getting-started/qa#which-files-should-be-gitignored
  - https://yarnpkg.com/features/zero-installs
  - https://yarnpkg.com/getting-started/install

**Comment by juancho0202** [comment]
About commit conventions: https://www.conventionalcommits.org/en/v1.0.0/
