### ISSUE TITLE
Open-scd-core is not exporting any typed mixins.

### ISSUE THREAD

**Issue by pascalwilbrink** [openscd/open-scd-core#88]
Open-scd-core is not exporting any typed mixins.
Therefore I cannot use a mixin inside a plugin.

Can these be exported by the foundation as well?

**Comment by Sander3003** [comment]
Let's refine this

**Comment by pascalwilbrink** [comment]
Discussion from Slack

pascal wilbrink
  [10:51 AM](https://lfenergy.slack.com/archives/C04B2LM6L64/p1676627473957419)
@openscd/open-scd-core is not exporting any Mixins (typed ones). Can this be fixed? Added a github issue here: https://github.com/openscd/open-scd-core/issues/88

[#88 Open-scd-core is not exporting any typed mixins.](https://github.com/openscd/open-scd-core/issues/88)
Open-scd-core is not exporting any typed mixins.  
Therefore I cannot use a mixin inside a plugin.
Can these be exported by the foundation as well?
<https://github.com/[openscd/open-scd-core](https://github.com/openscd/open-scd-core)|openscd/open-scd-core>openscd/open-scd-core | Feb 17th | Added by [GitHub](https://lfenergy.slack.com/services/B01U96QMF2B)
white_check_mark
eyes
raised_hands







Christian
  [11:09 AM](https://lfenergy.slack.com/archives/C04B2LM6L64/p1676628569416509)
Thanks, good idea!


pascal wilbrink
  [11:11 AM](https://lfenergy.slack.com/archives/C04B2LM6L64/p1676628670940039)
and what about the OpenSCD class?


Christian
  [11:11 AM](https://lfenergy.slack.com/archives/C04B2LM6L64/p1676628699326869)
I think we already export that from open-scd.ts, don't we? We could export the mixins from there as well. (edited) 


pascal wilbrink
  [11:12 AM](https://lfenergy.slack.com/archives/C04B2LM6L64/p1676628749270149)
https://www.npmjs.com/package/@openscd/open-scd-core?activeTab=explore
There's only a foundation.d.ts file in here, no open-scd.d.ts
[11:13](https://lfenergy.slack.com/archives/C04B2LM6L64/p1676628836600899)
import { OpenSCD } from '@openscd/open-scd-core/open-scd.js';  This doesn't work
import { OpenSCD } from '@openscd/open-scd-core'; Neither does this (edited) 


Christian
  [11:22 AM](https://lfenergy.slack.com/archives/C04B2LM6L64/p1676629377877379)
"compile": "tsc -b && tsc foundation.ts --declaration --emitDeclarationOnly --outDir dist", in package.json means we currently export types only for foundation.ts, we should add open-scd.ts to that command to fix that. We could do that in the same pull request which re-exports the mixins from open-scd.ts, what do you think?

**Comment by Sander3003** [comment]
This won't be necessary anymore if the OpenSCD class is exported. The issue will arrise again if we start with CoMPAS based on OpenSCD-core.

**Comment by danyill** [comment]
This is still an issue for me, I can't use open-scd-core in tests easily unless I either have the OpenSCD class (as a lit element with types) or I have mixins which I can wrap my plugin in.

So I'd like to re-open this and perhaps we can discuss at refinement.
